### ISSUE TITLE
Status bar is slightly smaller than it needs to be, blocking part of quick settings toggles

### ISSUE THREAD

**Issue by bituquinha** [PixelBuilds-Devices/android_device_google_crosshatch#1]
What happens:
When you slide the notification panel down, the status bar thickness is slightly smaller than it needs to be, and the notch blocks quick settings toggles partially.

What is expected:
The status bar should be thick enough to allow the quick settings toggles to sit below it unblocked.

First issue report, please let me know if any extra information is needed. Thank you

**Comment by alexismdr** [comment]
Already fixed in https://github.com/PixelBuilds-Devices/android_device_google_crosshatch/commit/6f8364db5c7cf2ae9bf670c7a8aefd14ad06e63d
Just wait for the next build
